"""experience record replaces base resume

Revision ID: 618c72959ded
Revises: c3f901b8828b
Create Date: 2026-09-20 19:55:46.792813
"""

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision = "618c72959ded"
down_revision = "c3f901b8828b"
branch_labels = None
depends_on = None


NEW_KINDS = ("resume", "cover_letter", "interview_prep", "portfolio", "offer_letter", "other")
OLD_KINDS = ("base_resume", "tailored_resume", "cover_letter", "portfolio", "offer_letter", "other")


def _swap_document_kind(new_values, mapping_sql):
    """Replace the document_kind enum, remapping existing rows.

    Written by hand: alembic autogenerate does not detect Postgres enum value
    changes, so it saw the dropped columns here but not this.
    """
    values = ", ".join(f"'{v}'" for v in new_values)
    op.execute("ALTER TYPE document_kind RENAME TO document_kind_old")
    op.execute(f"CREATE TYPE document_kind AS ENUM ({values})")
    op.execute("ALTER TABLE documents ALTER COLUMN kind DROP DEFAULT")
    op.execute(
        "ALTER TABLE documents ALTER COLUMN kind TYPE document_kind "
        f"USING ({mapping_sql})::document_kind"
    )
    op.execute("DROP TYPE document_kind_old")


def upgrade() -> None:
    # Both resume kinds collapse into one: a resume is now generated output,
    # not a master document other things point at.
    _swap_document_kind(
        NEW_KINDS,
        "CASE kind::text "
        "WHEN 'base_resume' THEN 'resume' "
        "WHEN 'tailored_resume' THEN 'resume' "
        "ELSE kind::text END",
    )

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "experience_profiles",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("full_name", sa.String(length=255), nullable=True),
        sa.Column("headline", sa.String(length=255), nullable=True),
        sa.Column("email", sa.String(length=255), nullable=True),
        sa.Column("phone", sa.String(length=64), nullable=True),
        sa.Column("location", sa.String(length=255), nullable=True),
        sa.Column("links", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("skills", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "resume_templates",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("is_default", sa.Boolean(), nullable=False),
        sa.Column("sections", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("options", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_index(
        "uq_resume_templates_single_default",
        "resume_templates",
        ["is_default"],
        unique=True,
        postgresql_where=sa.text("is_default"),
    )
    op.create_table(
        "experience_education",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("profile_id", sa.UUID(), nullable=False),
        sa.Column("institution", sa.String(length=255), nullable=False),
        sa.Column("credential", sa.String(length=255), nullable=True),
        sa.Column("field", sa.String(length=255), nullable=True),
        sa.Column("start_date", sa.Date(), nullable=True),
        sa.Column("end_date", sa.Date(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["profile_id"], ["experience_profiles.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_experience_education_profile_id"),
        "experience_education",
        ["profile_id"],
        unique=False,
    )
    op.create_table(
        "experience_messages",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("profile_id", sa.UUID(), nullable=False),
        sa.Column("role", sa.Enum("user", "assistant", name="chat_role"), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["profile_id"], ["experience_profiles.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_experience_messages_profile_id"),
        "experience_messages",
        ["profile_id"],
        unique=False,
    )
    op.create_table(
        "experience_roles",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("profile_id", sa.UUID(), nullable=False),
        sa.Column("company", sa.String(length=255), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("location", sa.String(length=255), nullable=True),
        sa.Column("employment_type", sa.String(length=64), nullable=True),
        sa.Column("start_date", sa.Date(), nullable=True),
        sa.Column("end_date", sa.Date(), nullable=True),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column(
            "source",
            sa.Enum("imported", "manual", "chat", name="experience_source"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["profile_id"], ["experience_profiles.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_experience_roles_profile_id"), "experience_roles", ["profile_id"], unique=False
    )
    op.create_table(
        "experience_highlights",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("role_id", sa.UUID(), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column(
            "source",
            sa.Enum("imported", "manual", "chat", name="experience_source"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["role_id"], ["experience_roles.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_experience_highlights_role_id"), "experience_highlights", ["role_id"], unique=False
    )
    op.create_table(
        "experience_stories",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("profile_id", sa.UUID(), nullable=False),
        sa.Column("role_id", sa.UUID(), nullable=True),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("skills", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "source",
            sa.Enum("imported", "manual", "chat", name="experience_source"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["profile_id"], ["experience_profiles.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["role_id"], ["experience_roles.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_experience_stories_profile_id"), "experience_stories", ["profile_id"], unique=False
    )
    op.create_index(
        op.f("ix_experience_stories_role_id"), "experience_stories", ["role_id"], unique=False
    )
    op.drop_index(op.f("ix_documents_derived_from_id"), table_name="documents")
    op.drop_index(
        op.f("uq_documents_single_base"), table_name="documents", postgresql_where="is_base"
    )
    op.drop_constraint(op.f("fk_documents_derived_from_id"), "documents", type_="foreignkey")
    op.drop_column("documents", "derived_from_id")
    op.drop_column("documents", "is_base")
    # ### end Alembic commands ###


def downgrade() -> None:
    _swap_document_kind(
        OLD_KINDS,
        "CASE kind::text "
        "WHEN 'resume' THEN 'base_resume' "
        "WHEN 'interview_prep' THEN 'other' "
        "ELSE kind::text END",
    )

    # ### commands auto generated by Alembic - please adjust! ###
    # server_default backfills the existing rows; autogenerate omits it and the
    # NOT NULL then fails on any non-empty table.
    op.add_column(
        "documents",
        sa.Column(
            "is_base",
            sa.BOOLEAN(),
            autoincrement=False,
            nullable=False,
            server_default=sa.false(),
        ),
    )
    op.alter_column("documents", "is_base", server_default=None)
    op.add_column(
        "documents", sa.Column("derived_from_id", sa.UUID(), autoincrement=False, nullable=True)
    )
    op.create_foreign_key(
        op.f("fk_documents_derived_from_id"),
        "documents",
        "documents",
        ["derived_from_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_index(
        op.f("uq_documents_single_base"),
        "documents",
        ["is_base"],
        unique=True,
        postgresql_where="is_base",
    )
    op.create_index(
        op.f("ix_documents_derived_from_id"), "documents", ["derived_from_id"], unique=False
    )
    op.drop_index(op.f("ix_experience_stories_role_id"), table_name="experience_stories")
    op.drop_index(op.f("ix_experience_stories_profile_id"), table_name="experience_stories")
    op.drop_table("experience_stories")
    op.drop_index(op.f("ix_experience_highlights_role_id"), table_name="experience_highlights")
    op.drop_table("experience_highlights")
    op.drop_index(op.f("ix_experience_roles_profile_id"), table_name="experience_roles")
    op.drop_table("experience_roles")
    op.drop_index(op.f("ix_experience_messages_profile_id"), table_name="experience_messages")
    op.drop_table("experience_messages")
    op.drop_index(op.f("ix_experience_education_profile_id"), table_name="experience_education")
    op.drop_table("experience_education")
    op.drop_index(
        "uq_resume_templates_single_default",
        table_name="resume_templates",
        postgresql_where=sa.text("is_default"),
    )
    op.drop_table("resume_templates")
    op.drop_table("experience_profiles")

    # drop_table leaves the enum types behind, which makes the next upgrade fail
    # with "type already exists". Alembic never emits these.
    op.execute("DROP TYPE IF EXISTS experience_source")
    op.execute("DROP TYPE IF EXISTS chat_role")
    # ### end Alembic commands ###
